core/part-2/ecommerce/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path
from .views import (
    ProductDetailView,
    add_to_cart,
    HomeView,
    ShopView,
    remove_from_cart,
    CheckoutView,
    CartView,
    contact,
    delete_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    )
app_name = 'core'
urlpatterns = [
    path('', HomeView.as_view(), name='HomeView'),
    path('productdetails/<slug>/', ProductDetailView.as_view(), name='productdetails'),
    path('shop/', ShopView.as_view(), name='ShopView'),
    path('cartview/', CartView.as_view(), name='cartview' ),
    path('add_to_cart/<slug>/', add_to_cart, name='add_to_cart'),
    path('add_coupon/', AddCouponView.as_view(), name='add_coupon'),
    path('remove_from_cart/<slug>/', remove_from_cart, name='remove_from_cart'),
    path('delete_from_cart/<slug>/', delete_from_cart, name='delete_from_cart'),
    path('checkout/',CheckoutView.as_view(), name='checkout'),
    path('contact', contact, name='contact'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),

]

onlineshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    

templates/pages/cart.html
{% extends "partial/base.html" %}
{% load static %}
{% block content %}
<!-- Breadcrumb Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="#">Home</a>
                <a class="breadcrumb-item text-dark" href="#">Shop</a>
                <span class="breadcrumb-item active">Shopping Cart</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->


<!-- Cart Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-light table-borderless table-hover text-center mb-0">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Products</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total</th>
                        <th scope="col">Remove</th>
                    </tr>
                </thead>

                {% for order_item in object.items.all %}
                <tbody class="align-middle">
                    <tr>
                        <td class="align-middle" scope="row">
                            {{ forloop.counter}}
                        </td>
                        <td class="align-middle"><img src="{% static 'img/product-1.jpg' %}" alt="" style="width: 50px;">{{order_item.item.title}}</td>
                        <td class="align-middle">${{order_item.item.price}}</td>
                        <td class="align-middle">
                            <div class="input-group quantity mx-auto" style="width: 100px;">
                                <div class="input-group-btn">
                                    <a class="btn btn-sm btn-primary btn-minus" href="{{order_item.item.get_remove_from_cart_url}}">
                                    <i class="fa fa-minus"></i>
                                    </a>
                                </div>
                                <input type="text" class="form-control form-control-sm bg-secondary border-0 text-center" value="{{order_item.quantity}}">
                                <div class="input-group-btn">
                                    <a class="btn btn-sm btn-primary btn-plus" href="{{order_item.item.get_add_to_cart_url}}">
                                        <i class="fa fa-plus"></i>
                                    </a>
                                </div>
                            </div>
                        </td>
                        <td class="align-middle">
                            {% if order_item.item.discount_price %} 
{% comment %} TODO: FIX DISCOUNT ERROR {% endcomment %}
                                   ${{order_item.get_total_discount_item_price}}
                                   <span class="badge badge-primary">(saving ${{order_item.get_amount_saved}})</span>

                             {% else %}

                                    ${{order_item.get_total_item_price }}

                              {% endif %}
                        </td>
                        <td class="align-middle"><a class="btn btn-sm btn-danger" href="{{object.get_delete_from_cart_url}}"><i class="fa fa-times"></i></a></td>
                    </tr>
                    <tr>
                        <td class="align-middle"><img src="{%  static 'img/product-2.jpg' %}" alt="" style="width: 50px;"> Product Name</td>
                        <td class="align-middle">$150</td>
                        <td class="align-middle">
                            <div class="input-group quantity mx-auto" style="width: 100px;">
                                <div class="input-group-btn">
                                    <button class="btn btn-sm btn-primary btn-minus" >
                                    <i class="fa fa-minus"></i>
                                    </button>
                                </div>
                                <input type="text" class="form-control form-control-sm bg-secondary border-0 text-center" value="0">
                                <div class="input-group-btn">
                                    <button class="btn btn-sm btn-primary btn-plus">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                </div>
                            </div>
                        </td>
                        <td class="align-middle">$150</td>
                        <td class="align-middle"><button class="btn btn-sm btn-danger"><i class="fa fa-times"></i></button></td>
                    </tr>
                    <tr>
                        <td class="align-middle"><img src="{% static 'img/product-3.jpg' %}" alt="" style="width: 50px;"> Product Name</td>
                        <td class="align-middle">$150</td>
                        <td class="align-middle">
                            <div class="input-group quantity mx-auto" style="width: 100px;">
                                <div class="input-group-btn">
                                    <button class="btn btn-sm btn-primary btn-minus" >
                                    <i class="fa fa-minus"></i>
                                    </button>
                                </div>
                                <input type="text" class="form-control form-control-sm bg-secondary border-0 text-center" value="1">
                                <div class="input-group-btn">
                                    <button class="btn btn-sm btn-primary btn-plus">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                </div>
                            </div>
                        </td>
                        <td class="align-middle">$150</td>
                        <td class="align-middle"><button class="btn btn-sm btn-danger"><i class="fa fa-times"></i></button></td>
                    </tr>
                    <tr>
                        <td class="align-middle"><img src="{% static 'img/product-4.jpg' %}" alt="" style="width: 50px;"> Product Name</td>
                        <td class="align-middle">$150</td>
                        <td class="align-middle">
                            <div class="input-group quantity mx-auto" style="width: 100px;">
                                <div class="input-group-btn">
                                    <button class="btn btn-sm btn-primary btn-minus" >
                                    <i class="fa fa-minus"></i>
                                    </button>
                                </div>
                                <input type="text" class="form-control form-control-sm bg-secondary border-0 text-center" value="1">
                                <div class="input-group-btn">
                                    <button class="btn btn-sm btn-primary btn-plus">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                </div>
                            </div>
                        </td>
                        <td class="align-middle">$150</td>
                                                
                        <td class="align-middle"><button class="btn btn-sm btn-danger"><i class="fa fa-times"></i></button></td>
                    </tr>
                    <tr>
                        <td class="align-middle"><img src="{% static 'img/product-5.jpg' %}" alt="" style="width: 50px;"> Product Name</td>
                        <td class="align-middle">$150</td>
                        <td class="align-middle">
                            <div class="input-group quantity mx-auto" style="width: 100px;">
                                <div class="input-group-btn">
                                    <button class="btn btn-sm btn-primary btn-minus" >
                                    <i class="fa fa-minus"></i>
                                    </button>
                                </div>
                                <input type="text" class="form-control form-control-sm bg-secondary border-0 text-center" value="1">
                                <div class="input-group-btn">
                                    <button class="btn btn-sm btn-primary btn-plus">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                </div>
                            </div>
                        </td>
                        <td class="align-middle">$150</td>
                        <td class="align-middle"><button class="btn btn-sm btn-danger"><i class="fa fa-times"></i></button></td>
                    </tr>

                    {% comment %} if cart is empty {% endcomment %}
                    {% empty %}
                         <td colspan="6">Your cart is empy</td>

                </tbody>

                {% endfor %}
            </table>
        </div>
       
        <div class="col-lg-4">
            {% comment %} {% if DISPLAY_COUPON_FORM%} {% endcomment %}
            <form method="POST" class="mb-30" action="{% url 'core:add_coupon' %}">
                {% csrf_token %}
                <div class="input-group">
                    <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">
                    {{couponform.code}}
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">Apply Coupon</button>
                    </div>
                </div>
            </form>
            {% comment %} {% endif %} {% endcomment %}
            
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
            {% if object.get_total%}
            <div class="bg-light p-30 mb-5">
                <div class="border-bottom pb-2">
                    {% if user.is_authenticated %}
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Total Items</h6>
                            {% comment %} TODO: FIX {{ object.get_total_items }} error {% endcomment %}
                            <h6>{{ object.get_total_items }}</h6>
                        </div>
                        {% if object.coupon %}
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Coupon Code</h6>
                            <h6>{{ object.coupon.code }}</h6>
                        </div>
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Coupon Points</h6>
                            <h6>-${{ object.coupon.amount }}</h6>
                        </div>
                        {% endif %}
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Subtotal</h6>
                            <h6>${{ object.get_total }}</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Shipping</h6>
                            <h6 class="font-weight-medium">$10</h6>
                        </div>
                    {% else %}
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Total Items</h6>
                            <h6>(11)</h6>
                        </div>
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Subtotal</h6>
                            <h6>${{ object.get_total}}</h6>
                        </div>
                    {% endif %}

                    {% comment %} Total cost plus shipping cost {% endcomment %}
                </div>
                <div class="pt-2">
                    <div class="d-flex justify-content-between mt-2">
                        <h5>Total</h5>
                        <h5>$150</h5>
                    </div>
                    <a class="btn btn-block btn-warning font-weight-bold my-3 py-3" href="/checkout/">Proceed To Checkout</a>
                    <a class="btn btn-block btn-primary font-weight-bold my-3 py-3" href="/">Continue Shopping</a>
                </div>
            </div>
            {% else %}
{% comment %} if cart is empty {% endcomment %}
                    <div class="pt-2">
                    
                        <a class="btn btn-block btn-primary font-weight-bold my-3 py-3" href="/">Start Shopping</a>

                    </div>
                            
            {% endif %}
        </div>
    </div>
</div>
<!-- Cart End -->

{% endblock content %}

templates/pages/contact.html
{% extends  "partial/base.html" %}

{% load static %}

{% block content %}

 <!-- Breadcrumb Start -->
 <div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="#">Home</a>
                <span class="breadcrumb-item active">Contact</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->


<!-- Contact Start -->
<div class="container-fluid">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Contact Us</span></h2>
    <div class="row px-xl-5">
        <div class="col-lg-7 mb-5">
            <div class="contact-form bg-light p-30">
                <div id="success"></div>
                <form name="sentMessage" id="contactForm" novalidate="novalidate">
                    <div class="control-group">
                        <input type="text" class="form-control" id="name" placeholder="Your Name"
                            required="required" data-validation-required-message="Please enter your name" />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        <input type="email" class="form-control" id="email" placeholder="Your Email"
                            required="required" data-validation-required-message="Please enter your email" />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        <input type="text" class="form-control" id="subject" placeholder="Subject"
                            required="required" data-validation-required-message="Please enter a subject" />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        <textarea class="form-control" rows="8" id="message" placeholder="Message"
                            required="required"
                            data-validation-required-message="Please enter your message"></textarea>
                        <p class="help-block text-danger"></p>
                    </div>
                    <div>
                        <button class="btn btn-primary py-2 px-4" type="submit" id="sendMessageButton">Send
                            Message</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-5 mb-5">
            <div class="bg-light p-30 mb-30">
                <iframe style="width: 100%; height: 250px;"
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
                frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div>
            <div class="bg-light p-30 mb-3">
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-2"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
            </div>
        </div>
    </div>
</div>
<!-- Contact End -->

{% endblock content%}

templates/pages/payment.html
{% extends "partial/base.html" %}

{% load static %}

{% block extra_head %}
<style>

#stripeBtnLabel {
  font-family: "Helvetica Neue", Helvetica, sans-serif;
  font-size: 16px;
  font-variant: normal;
  padding: 0;
  margin: 0;
  -webkit-font-smoothing: antialiased;
  font-weight: 500;
  display: block;
}

#stripeBtn {
  border: none;
  border-radius: 4px;
  outline: none;
  text-decoration: none;
  color: #fff;
  background: #32325d;
  white-space: nowrap;
  display: inline-block;
  height: 40px;
  line-height: 40px;
  box-shadow: 0 4px 6px rgba(50, 50, 93, .11), 0 1px 3px rgba(0, 0, 0, .08);
  border-radius: 4px;
  font-size: 15px;
  font-weight: 600;
  letter-spacing: 0.025em;
  text-decoration: none;
  -webkit-transition: all 150ms ease;
  transition: all 150ms ease;
  float: left;
  width: 100%
}

button:hover {
  transform: translateY(-1px);
  box-shadow: 0 7px 14px rgba(50, 50, 93, .10), 0 3px 6px rgba(0, 0, 0, .08);
  background-color: #43458b;
}

.stripe-form {
  padding: 5px 30px;
}

#card-errors {
  height: 20px;
  padding: 4px 0;
  color: #fa755a;
}

.stripe-form-row {
  width: 100%;
  float: left;
  margin-top: 5px;
  margin-bottom: 5px;
}

/**
 * The CSS shown here will not be introduced in the Quickstart guide, but shows
 * how you can use CSS to style your Element's container.
 */
.StripeElement {
  box-sizing: border-box;

  height: 40px;

  padding: 10px 12px;

  border: 1px solid transparent;
  border-radius: 4px;
  background-color: white;

  box-shadow: 0 1px 3px 0 #e6ebf1;
  -webkit-transition: box-shadow 150ms ease;
  transition: box-shadow 150ms ease;
}

.StripeElement--focus {
  box-shadow: 0 1px 3px 0 #cfd7df;
}

.StripeElement--invalid {
  border-color: #fa755a;
}

.StripeElement--webkit-autofill {
  background-color: #fefde5 !important;
}

.current-card-form {
  display: none;
}

</style>
{% endblock extra_head %}

{% block content %}
 <!-- Breadcrumb Start -->
 <div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="#">Home</a>
                <a class="breadcrumb-item text-dark" href="#">Shop</a>
                <span class="breadcrumb-item active">Checkout</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->


<!-- Checkout Start -->
<div class="container-fluid">
   
        <div class="row px-xl-5">
            <div class="col-lg-8">
                {% if card %}
                <div style="padding: 5px 30px;">
                  <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" name="use_default_card" id="use_default_card">
                    <label class="custom-control-label" for="use_default_card">Use default card:
                      **** **** **** {{ card.last4 }} 
                    <span>Exp: {{ card.exp_month }}/{{ card.exp_year }}</span></label>
                    </div>
                  </div>
                {% endif %}
                <div class="current-card-form">
                    <form action="." method="post" class="stripe-form">
                        {% csrf_token %}
                        <input type="hidden" name="use_default" value="true">
                        <div class="stripe-form-row">
                          <button id="stripeBtn">Submit Payment</button>
                        </div>
                        <div id="card-errors" role="alert"></div>
                    </form>
                </div>

                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Payment</span></h5>
                <div class="bg-light p-30 mb-5  new-card-form" >
                    <form method="POST" class="stripe-form" action="."  id="stripe-form">
                        {% csrf_token %}
                    
                        <div class="row">

                            <div class="stripe-form-row" id="creditCard">
                                <label for="card-element" id="stripeBtnLabel">
                                    Credit or debit card
                                </label>
                                <div id="card-element" class="StripeElement StripeElement--empty">
                                    <!-- A Stripe Element will be inserted here. -->
                                    <div class="__PrivateStripeElement" style="margin: 0px !important; padding: 0px !important; border: none !important; display: block !important; background: transparent !important; position: relative !important; opacity: 1 !important;">
                                        <iframe frameborder="0" allowtransparency="true" scrolling="no" name="__privateStripeFrame5" allowpaymentrequest="true" src="https://js.stripe.com/v3/elements-inner-card-19066928f2ed1ba3ffada645e45f5b50.html#style[base][color]=%2332325d&amp;style[base][fontFamily]=%22Helvetica+Neue%22%2C+Helvetica%2C+sans-serif&amp;style[base][fontSmoothing]=antialiased&amp;style[base][fontSize]=16px&amp;style[base][::placeholder][color]=%23aab7c4&amp;style[invalid][color]=%23fa755a&amp;style[invalid][iconColor]=%23fa755a&amp;componentName=card&amp;wait=false&amp;rtl=false&amp;keyMode=test&amp;origin=https%3A%2F%2Fstripe.com&amp;referrer=https%3A%2F%2Fstripe.com%2Fdocs%2Fstripe-js&amp;controllerId=__privateStripeController1" title="Secure payment input frame" style="border: none !important; margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; overflow: hidden !important; display: block !important; height: 19.2px;">

                                        </iframe>
                                        <input class="__PrivateStripeElement-input form-control" aria-hidden="true" aria-label=" " autocomplete="false" maxlength="1" style="border: none !important; display: block !important; position: absolute !important; height: 1px !important; top: 0px !important; left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; background: transparent !important; pointer-events: none !important; font-size: 16px !important;">
                                    </div>
                                </div>

                            </div>

                            <div class="stripe-form-row">
                                <button id="stripeBtn" >Submit Payment</button>
                            </div>

                            <div class="stripe-form-row">
                                <div class="custom-control custom-checkbox">
                                  <input type="checkbox" class="custom-control-input" name="save" id="save_card_info">
                                  <label class="custom-control-label" for="save_card_info">Save for future purchases</label>
                                </div>
                              </div>
                              <div id="card-errors" role="alert"></div>


                        </div>

                    </form>

                </div>
                
            </div>
            <div class="col-lg-4">
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Order Total</span></h5>
                <div class="bg-light p-30 mb-5">

                    {% for order_item in order.items.all %}

                      <div class="border-bottom">
                          <h6 class="mb-3">Products</h6>
                          <div class="d-flex justify-content-between">
                              <p>{{order_item.item.title}} * {{order_item.quantity}}</p>
                              <p>${{order_item.get_final_price}}</p>
                          </div>
                      </div>

                    {% endfor %}
                    {% if order_item > 2 %}
                        <div class="border-bottom pt-3 pb-2">
                          <div class="d-flex justify-content-between mb-3">
                                <h6>Total Products</h6>
                                <h6>{{order.items.count}}</h6>
                          </div>
                          <div class="d-flex justify-content-between mb-3">
                                <h6>Total Items</h6>
                                <h6>{{ order.get_total_items }}</h6>
                            </div>
                            <div class="d-flex justify-content-between mb-3">
                                <h6>Subtotal</h6>
                                <h6>${{order.get_total}}</h6>
                            </div>
                            <div class="d-flex justify-content-between">
                                <h6 class="font-weight-medium">Shipping</h6>
                                <h6 class="font-weight-medium">$10</h6>
                            </div>
                        </div>
                    {% else %}
                        <div class="d-flex justify-content-between mb-3">
                          <h6>Total Products</h6>
                          <h6>{{order.items.count}}</h6>
                        </div>
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Subtotal</h6>
                            <h6>${{order.get_total}}</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Shipping</h6>
                            <h6 class="font-weight-medium">$10</h6>
                        </div>
                    {% endif %}
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>$160</h5>
                        </div>
                    </div>
                </div>
            
            </div>
        </div>
</div>
<!-- Checkout End -->

{% endblock %}


{% block extra_scripts %}

<script src="https://js.stripe.com/v3/"></script>

 <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script nonce="">
    // Create a Stripe client
    var stripe = Stripe({{STRIPE_PUBLISHABLE_KEY}});

    // Create an instance of Elements
    var elements = stripe.elements();

    // Custom styling can be passed to options when creating an Element.
    // (Note that this demo uses a wider set of styles than the guide below.)
    var style = {
        base: {
        color: '#32325d',
        fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
        fontSmoothing: 'antialiased',
        fontSize: '16px',
        '::placeholder': {
            color: '#aab7c4'
        }
        },
        invalid: {
        color: '#fa755a',
        iconColor: '#fa755a'
        }
    };

    // Create a card Element and mount it to the DOM
    var card = elements.create('card', {style: style});

    //Add an instance of the card Element into the 'card-element' <div>
    card.mount('#card-element');

    // Handle real-time validation errors from the card Element.
    card.addEventListener('change', function(event) {
        var displayError = document.getElementById('card-errors');
        if (event.error) {
        displayError.textContent = event.error.message;
        } else {
        displayError.textContent = '';
        }
    });

    // Handle form submission
    var form = document.getElementById('stripe-form');
    form.addEventListener('submit', function(event) {
        event.preventDefault();

        stripe.createToken(card).then(function(result) {
            if (result.error) {
                // Inform the user if there was an error
                var errorElement = document.getElementById('card-errors');
                errorElement.textContent = result.error.message;
            } else {
                // Send the token to your server
                stripeTokenHandler(result.token);
            }
        });
    });

    // Submit the form with the token ID.
    function stripeTokenHandler(token) {
        // Insert the token ID into the form so it gets submitted to the server
        var form = document.getElementById('stripe-form');
        var hiddenInput = document.createElement('input');
        hiddenInput.setAttribute('type', 'hidden');
        hiddenInput.setAttribute('name',stripeToken);
        hiddenInput.setAttribute('value', token.id);
        form.appendChild(hiddenInput);

        // Submit the form
        form.submit();
    }

    var currentCardForm = $('.current-card-form');
    var newCardForm = $('.new-card-form');
    var use_default_card = document.querySelector("input[name=use_default_card]");
    use_default_card.addEventListener('change', function() {
      if (this.checked) {
        newCardForm.hide();
        currentCardForm.show()
      } else {
        newCardForm.show();
        currentCardForm.hide()
      }
    })
</script>

{% endblock extra_scripts %}